- name: "Demo de Automatización Ansible Red Hat"
  hosts: all
  remote_user: root
  tasks:
    - name: "Inicio de Prueba"
      debug:
       msg: "Automatización de Procesos desde Ansible a SUSE"
    - name: "Asignando nombre al host"
      command: hostnamectl set-hostname banregio.demo.com
    - name: "Actualizando a última version Sistema Operativo"
      zypper: name=* state=latest type=patch
    - name: "Instalando Servicios WEB"
      zypper: name=apache2 state=present disable_recommends=no
    - name: "Iniciando Servicios WEB"
      service: name=apache2 state=restarted
    - name: "Servicio WEB DISPONIBLE"
      command: systemctl enable apache2.service
    - name: "Generando Página Principal"
      command: wget https://www.banregio.com -O /srv/www/htdocs/index.html
