- name: "Demo de Automatizacion Ansible Red Hat"
  hosts: all
  remote_user: root
  tasks:
    - name: Prueba de Automatizacion para Banregio Suse Update
      debug:
       msg: "Automatización de procesos desde Ansible a SUSE"
    - name: "Asignando nombre al host"
      hostname: name=banregio.demo.com
    - name: "Actualizando a última version Sistema Operativo"
      zypper: name=* state=latest type=patch
    - name: "Instalando Apache"
      zypper: name=apache2 state=present disable_recommends=no
    - name: "Iniciando Apache"
      service: name=apache2 state=restarted
    - name: "Servicio Web"
      command: systemctl enable apache2.service
      command: wget https://www.banregio.com -O /srv/www/htdocs/index.html
